[
  {
    category: "mobiles",
    title: "Apple iPhone 14",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    price: 89999,
    description: "Apple iPhone 14 (128 GB) - Blue",
  },
  {
    category: "laptops",
    title: "Xiaomi [Smartchoice] Notebookpro",
    imgSrc: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
    description: "Xiaomi [Smartchoice] Notebookpro",
    price: 49999,
  },
  {
    category: "tablets",
    title: "Xiaomi Pad 6",
    imgSrc: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
    description: "Xiaomi Pad 6| Qualcomm Snapdragon 870|",
    price: 29999,
  },
  {
    category: "mobiles",
    title: "Apple iPhone 11",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    description: "Apple iPhone 11 (64GB) - White",
    price: 79999,
  },
  {
    category: "tablets",
    title: "Lenovo Tab P12 AMOLED",
    imgSrc: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
    description: "Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm)",
    price: 19999,
  },
  {
    category: "mobiles",
    title: "Apple iPhone 13",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    description: "Apple iPhone 13 (128GB) - Blue",
    price: 69999,
  },
  {
    category: "laptops",
    title: "Lenovo IdeaPad Slim 5",
    imgSrc: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
    description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm)',
    price: 29999,
  },
  {
    category: "tablets",
    title: "Samsung Galaxy Tab A8",
    imgSrc: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
    description: "Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB",
    price: 49999,
  },
  {
    category: "laptops",
    title: "Apple MacBook Air Laptop",
    imgSrc: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
    description: "Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74",
    price: 89999,
  },
];
